version: '3'

networks:
  isolation-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    command: npm run start:dev
    environment:
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - '8001:8001'
    volumes:
      - .:/usr/src/app
    networks:
      - isolation-network

  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    ports:
      - '8000:8000'
    networks:
      - isolation-network
